CREATE TABLE IF NOT EXISTS logistics_operators (id INT PRIMARY KEY, Operator VARCHAR(255), Team CHAR(1));
INSERT INTO logistics_operators (id, Operator, Team) VALUES (0, 'Laura Ferraro', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (1, 'Aldo Messina', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (2, 'Nino Grasso', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (3, 'Fulvio Ferrara', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (4, 'Nadia Riva', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (5, 'Michela De Luca', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (6, 'Simona Palumbo', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (7, 'Simone Rinaldi', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (8, 'Teresa Vitale', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (9, 'Lina Grassi', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (10, 'Silvio De Angelis', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (11, 'Daniele Li', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (12, 'Giovanna Marini', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (13, 'Davide Mazza', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (14, 'Filippo Barone', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (15, 'Anna Caruso', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (16, 'Patrizia Bruno', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (17, 'Aldo Vasiliauskas', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (18, 'Ling Martini', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (19, 'Gianni Farina', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (20, 'Jun Pirlo', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (21, 'Filippo D''Angelo', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (22, 'Giovanni Marino', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (23, 'Fabio Pirlo', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (24, 'Leandro Lombardo', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (25, 'Benito Messina', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (26, 'Salvatore Russo', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (27, 'Marco Caputo', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (28, 'Andrius Bianchi', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (29, 'Daniela Galli', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (30, 'Giulio Ricci', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (31, 'Valeria De Angelis', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (32, 'Giorgio Leone', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (33, 'Antonella De Angelis', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (34, 'Anjali Marino', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (35, 'Davide Bianchi', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (36, 'Piero Marotta', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (37, 'Luca Falcone', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (38, 'Stefano Barbieri', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (39, 'Giuseppina Colombo', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (40, 'Carmela De Angelis', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (41, 'Cesare Barbieri', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (42, 'Maurizio Parisi', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (43, 'Fulvio Ivanov', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (44, 'Pietro Greco', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (45, 'Giulia Sorrentino', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (46, 'Lorenzo Marini', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (47, 'Luigi Amato', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (48, 'Marco Conte', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (49, 'Gabriella Sala', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (50, 'Laura Orlando', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (51, 'Giacomo Giuliani', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (52, 'Marcello Zhang', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (53, 'Marcello Bianchi', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (54, 'Ling Ferretti', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (55, 'Anna Vasiliauskas', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (56, 'Sanjay Riva', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (57, 'Giuseppina Marchetti', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (58, 'Giuseppina Galli', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (59, 'Paolo Falcone', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (60, 'Michela Pirlo', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (61, 'Daniele Sala', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (62, 'Michela Riva', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (63, 'Nino Forte', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (64, 'Arturo Costa', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (65, 'Emilio Costa', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (66, 'Maurizio Bernardi', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (67, 'Rosaria Palmieri', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (68, 'Nino Orlando', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (69, 'Ivan Longo', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (70, 'Franco Amato', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (71, 'Mei Bellini', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (72, 'Eleonora Ferri', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (73, 'Raffaele Messina', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (74, 'Bruno Gallo', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (75, 'Federica Marotta', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (76, 'Giovanni Donati', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (77, 'Jun Mancini', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (78, 'Wei Ricciardi', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (79, 'Silvio Moretti', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (80, 'Giulia Santoro', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (81, 'Roberta Pirlo', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (82, 'Gabriella Palmieri', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (83, 'Sofia Brambilla', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (84, 'Valentino Palmieri', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (85, 'Giovanni Bernardi', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (86, 'Leonardo Pellegrini', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (87, 'Salvatore Singh', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (88, 'Claudio Bernardi', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (89, 'Darius D''Angelo', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (90, 'Silvio Popov', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (91, 'Aldo Forte', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (92, 'Roberta Martino', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (93, 'Marcello Forte', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (94, 'Riccardo Marchi', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (95, 'Michela Sokolov', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (96, 'Elena Serra', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (97, 'Elio Rossetti', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (98, 'Umberto Mariani', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (99, 'Rūta D''Angelo', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (100, 'Priya Ferrara', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (101, 'Elena Amato', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (102, 'Raffaele Rinaldi', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (103, 'Leandro Jankauskas', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (104, 'Chiara Mazza', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (105, 'Franco Mikalauskas', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (106, 'Umberto Gallo', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (107, 'Adriano Smirnov', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (108, 'Mario Marino', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (109, 'Anna Romano', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (110, 'Cristina Pellegrini', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (111, 'Lina Leone', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (112, 'Sofia Vasiliauskas', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (113, 'Dmitry Vitale', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (114, 'Marta Bianco', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (115, 'Arturo Mancini', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (116, 'Cosimo Pellegrini', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (117, 'Nadia Palumbo', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (118, 'Teresa Kuznetsov', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (119, 'Marta Silvestri', 'D');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (120, 'Patrizia Piazza', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (121, 'Elio Stefanelli', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (122, 'Giulia Serra', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (123, 'Anjali Sanna', 'C');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (124, 'Elia De Rosa', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (125, 'Eglė Marotta', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (126, 'Cesare Barone', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (127, 'Giacomo Messina', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (128, 'Marta Galli', 'E');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (129, 'Emilio Romano', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (130, 'Emilio Fiore', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (131, 'Matteo Santoro', 'B');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (132, 'Sara Lombardi', 'A');
INSERT INTO logistics_operators (id, Operator, Team) VALUES (133, 'Gianni Palumbo', 'C');
CREATE TABLE IF NOT EXISTS logistics_vehicles (id INT PRIMARY KEY, Vehicle VARCHAR(255), Brand VARCHAR(255), Purchased INT);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (0, 'Vesta SW Cross', 'Lada', 2014);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (1, 'Stratos', 'Lancia', 2012);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (2, 'Freemont', 'Fiat', 2010);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (3, '4320', 'Roman', 2002);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (4, 'Freemont', 'Fiat', 2008);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (5, 'Stelvio', 'Alfa Romeo', 2014);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (6, '1234', 'Roman', 2001);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (7, 'GAZelle Next', 'GAZ', 2002);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (8, 'Tigr', 'GAZ', 2017);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (9, '1234', 'Roman', 2019);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (10, 'Thema', 'Lancia', 2021);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (11, 'Stelvio', 'Alfa Romeo', 2003);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (12, 'Freemont', 'Fiat', 2001);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (13, 'Stratos', 'Lancia', 2005);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (14, '1124', 'Roman', 2020);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (15, 'Stratos', 'Lancia', 2005);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (16, 'Stelvio', 'Alfa Romeo', 2018);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (17, 'Patriot', 'UAZ', 2012);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (18, 'Jogger', 'Dacia', 2024);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (19, 'Thesis', 'Lancia', 2007);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (20, 'Hunter', 'UAZ', 2009);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (21, 'GAZelle Next', 'GAZ', 2008);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (22, 'Stratos', 'Lancia', 2009);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (23, 'Jogger', 'Dacia', 2009);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (24, 'Stratos', 'Lancia', 2005);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (25, 'GAZelle Next', 'GAZ', 2003);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (26, 'Bukhanka', 'UAZ', 2018);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (27, 'Thesis', 'Lancia', 2001);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (28, 'Giulia', 'Alfa Romeo', 2014);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (29, '4320', 'Roman', 2009);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (30, 'Thesis', 'Lancia', 2022);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (31, 'Thesis', 'Lancia', 2015);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (32, '1124', 'Roman', 2000);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (33, 'Jogger', 'Dacia', 2009);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (34, 'Thesis', 'Lancia', 2003);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (35, 'Vesta SW Cross', 'Lada', 1999);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (36, 'Hunter', 'UAZ', 2022);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (37, 'Thesis', 'Lancia', 2007);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (38, 'Toro', 'Fiat', 2003);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (39, 'Thesis', 'Lancia', 2017);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (40, 'Stelvio', 'Alfa Romeo', 2016);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (41, 'Toro', 'Fiat', 2009);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (42, 'Hunter', 'UAZ', 2005);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (43, 'Jogger', 'Dacia', 2010);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (44, '4x4 Vision', 'Lada', 2002);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (45, 'Stratos', 'Lancia', 2011);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (46, 'Patriot', 'UAZ', 2018);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (47, '1234', 'Roman', 2019);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (48, 'Tigr', 'GAZ', 2006);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (49, 'Freemont', 'Fiat', 2000);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (50, 'Sobol', 'GAZ', 2016);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (51, 'Toro', 'Fiat', 1999);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (52, '4320', 'Roman', 2014);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (53, 'Stratos', 'Lancia', 2006);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (54, 'Jogger', 'Dacia', 2006);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (55, '1234', 'Roman', 2004);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (56, 'Freemont', 'Fiat', 2023);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (57, 'Thema', 'Lancia', 2007);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (58, 'Freemont', 'Fiat', 2016);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (59, 'Jogger', 'Dacia', 2016);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (60, 'Toro', 'Fiat', 2009);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (61, 'Thesis', 'Lancia', 2008);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (62, '1124', 'Roman', 2012);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (63, 'Sobol', 'GAZ', 2020);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (64, 'Patriot', 'UAZ', 2002);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (65, 'Duster', 'Dacia', 2000);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (66, 'Freemont', 'Fiat', 2024);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (67, 'Sobol', 'GAZ', 2008);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (68, 'Stelvio', 'Alfa Romeo', 2005);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (69, 'Vesta SW Cross', 'Lada', 2019);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (70, 'Jogger', 'Dacia', 1999);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (71, 'Bukhanka', 'UAZ', 2010);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (72, 'Stelvio', 'Alfa Romeo', 2008);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (73, 'Sobol', 'GAZ', 2016);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (74, 'Jogger', 'Dacia', 2015);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (75, 'Jogger', 'Dacia', 2010);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (76, 'Vesta SW Cross', 'Lada', 2013);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (77, 'Jogger', 'Dacia', 2015);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (78, 'Jogger', 'Dacia', 2006);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (79, '4320', 'Roman', 2010);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (80, 'Jogger', 'Dacia', 2006);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (81, 'Stelvio', 'Alfa Romeo', 2017);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (82, 'Hunter', 'UAZ', 2023);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (83, 'Hunter', 'UAZ', 2002);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (84, '1124', 'Roman', 2011);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (85, 'Thesis', 'Lancia', 2024);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (86, 'Freemont', 'Fiat', 2002);
INSERT INTO logistics_vehicles (id, Vehicle, Brand, Purchased) VALUES (87, 'Giulia', 'Alfa Romeo', 2006);